function figure1=insetfitfigure2(X1, Y1,state_flag)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Aug-2011 11:13:32

% Create figure
figure1 = figure;%('XVisual','');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-2 3]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,Y1,'Parent',axes1,'LineWidth',2);

if state_flag==1
set(plot1(1),'Color',[0 0 1],'DisplayName','State One');
title('State One')
end

if state_flag==2
set(plot1(1),'Color',[1 0 0],'DisplayName','State Two');
title('State Two')
end
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[1 1 1],'FontSize',13);  %'YColor',[1 1 1],'XColor',[1 1 1],...
    

