function [figure1,X1,Y1]=mainfitfigure(xvector1, yvector1, X1, Y1)
%CREATEFIGURE(XVECTOR1,YVECTOR1,X1,Y1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 24-Aug-2011 11:11:39

% Create figure
%figure1 = figure('XVisual','');
figure1=figure;
% Create axes
axes1 = axes('Parent',figure1,'FontSize',20,'Position',[0.13 0.157142857142857 0.775 0.767857142857143]);

hold(axes1,'on');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-2 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 2]);
box(axes1,'on');
hold(axes1,'all');

% Create bar
bar(xvector1,yvector1,'FaceColor','none','LineWidth',2,'BarWidth',1);

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[0 0.498039215803146 0]);

% Create xlabel
xlabel('\DeltaX (\mum)','FontSize',20);

% Create ylabel
ylabel('Frequency (Normalized)/Probability Density','FontSize',20);

